import { getCapitalGains, resolveAssetType } from '../src/logic.ts';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const supabase = createClient(
  process.env.VITE_SUPABASE_URL!,
  process.env.VITE_SUPABASE_ANON_KEY!
);

async function testCG() {
  console.log('=== TESTING CAPITAL GAINS FOR SAAHIL PORTFOLIO (PFID 36 / ACID 36 / PFID 1) ===\n');

  // Let's check all assets in acmac1 that have Digitide or Bluspring
  const { data: acmac1 } = await supabase.from('acmac1').select('*');
  const dAssets = acmac1?.filter(a => a.name.includes('Digitide') || a.name.includes('Bluspring') || a.name.includes('Silver') || a.name.includes('HDFC Bank'));
  
  console.log('Target assets in ACMAC1:');
  dAssets?.forEach(a => console.log(`  - ID: ${a.id}, Name: ${a.name}, Acid: ${a.acid}, ATYID: ${a.atyid}`));

  // Check transc1 for Digitide & Bluspring
  const targetIds = dAssets?.map(a => a.id) || [];
  const { data: txs } = await supabase.from('transc1').select('*').in('maid', targetIds);
  console.log('\nTarget transactions in TRANSC1:');
  txs?.forEach(t => console.log(`  - VID: ${t.vid}, MAID: ${t.maid}, PFID: ${t.pfid}, Date: ${t.dt}, Dramt (Buy): ${t.dramt}, Cramt (Sell): ${t.cramt}, Qty: ${t.qnt}`));

  // Let's run getCapitalGains for portfolios 1..100
  const portIds = [1, 4, 30, 32, 36, 61];
  const gains = getCapitalGains(portIds, '2025-04-01', '2026-03-31');

  console.log(`\nTotal CG Matches generated by engine: ${gains.length}`);

  const digitideGains = gains.filter((g: any) => g.assetName?.includes('Digitide'));
  const bluspringGains = gains.filter((g: any) => g.assetName?.includes('Bluspring'));
  const silverGains = gains.filter((g: any) => g.assetName?.includes('Silver'));
  const hdfcGains = gains.filter((g: any) => g.assetName?.includes('HDFC Bank'));

  console.log(`Digitide Gains count: ${digitideGains.length}`);
  digitideGains.forEach((g: any) => console.log('  ', g));

  console.log(`Bluspring Gains count: ${bluspringGains.length}`);
  bluspringGains.forEach((g: any) => console.log('  ', g));

  console.log(`Silver Gains count: ${silverGains.length}`);
  silverGains.forEach((g: any) => console.log('  ', g));

  console.log(`HDFC Gains count: ${hdfcGains.length}`);
  hdfcGains.forEach((g: any) => console.log('  ', g));
}

testCG().catch(console.error);
