import json

data = {
  "groups": [
    {"id":"aif","name":"AIF","parent":"investments","type":"ASSET"},
    {"id":"art","name":"Art","parent":"fixed_assets","type":"ASSET"},
    {"id":"bank","name":"Banks","parent":"current_assets","type":"ASSET"},
    {"id":"capital_account","name":"Capital Account","type":"LIABILITY"},
    {"id":"capital_gains","name":"Capital Gains","parent":"income","type":"INCOME"},
    {"id":"cash","name":"Cash-in-Hand","parent":"current_assets","type":"ASSET"},
    {"id":"current_assets","name":"Current Assets","type":"ASSET"},
    {"id":"current_liabilities","name":"Current Liabilities","type":"LIABILITY"},
    {"id":"debtors","name":"Sundry Debtors","parent":"current_assets","type":"ASSET"},
    {"id":"deposits_loans","name":"Deposits / Loans","parent":"current_assets","type":"ASSET"},
    {"id":"duties_taxes","name":"Duties & Taxes","type":"LIABILITY"},
    {"id":"expenses","name":"Expenses","parent":"profit_loss","type":"EXPENSE"},
    {"id":"fds","name":"FDs","parent":"investments","type":"ASSET"},
    {"id":"fixed_assets","name":"Fixed Asset","type":"ASSET"},
    {"id":"gold","name":"Gold","parent":"fixed_assets","type":"ASSET"},
    {"id":"household_expense","name":"Household Expense","parent":"expenses","type":"EXPENSE"},
    {"id":"income","name":"Income","parent":"profit_loss","type":"INCOME"},
    {"id":"income_tax","name":"Income Tax","parent":"expenses","type":"EXPENSE"},
    {"id":"insurance_asset","name":"Insurance","parent":"investments","type":"ASSET"},
    {"id":"insurance_premium","name":"Insurance Premium","parent":"expenses","type":"EXPENSE"},
    {"id":"interest_saving","name":"Interest on Saving Account","parent":"income","type":"INCOME"},
    {"id":"investments","name":"Investments","type":"ASSET"},
    {"id":"jewellery","name":"Jewellery","parent":"fixed_assets","type":"ASSET"},
    {"id":"loans_asset","name":"Loans and Advances (Asset)","parent":"current_assets","type":"ASSET"},
    {"id":"loans_liability","name":"Loans (Liability)","type":"LIABILITY"},
    {"id":"mf_debt","name":"Mutual Funds(Debt)","parent":"investments","type":"ASSET"},
    {"id":"mf_equity","name":"Mutual Funds(Equity)","parent":"investments","type":"ASSET"},
    {"id":"misc_assets","name":"Misc Assets","type":"ASSET"},
    {"id":"ncd_debentures","name":"NCD/Debentures","parent":"investments","type":"ASSET"},
    {"id":"nps_uup","name":"NPS/UUP","parent":"investments","type":"ASSET"},
    {"id":"pms_aif","name":"PMS / AIF","parent":"investments","type":"ASSET"},
    {"id":"post_office","name":"Post Office","parent":"investments","type":"ASSET"},
    {"id":"ppf_epf","name":"PPF/EPF","parent":"investments","type":"ASSET"},
    {"id":"private_equity","name":"Private Equity","parent":"investments","type":"ASSET"},
    {"id":"profit_loss","name":"Profit & Loss","type":"LIABILITY"},
    {"id":"property","name":"Properties","parent":"fixed_assets","type":"ASSET"},
    {"id":"provisions","name":"Provisions","type":"LIABILITY"},
    {"id":"share_txn_charges","name":"Share Transaction Charges","parent":"expenses","type":"EXPENSE"},
    {"id":"silver","name":"Silver","parent":"fixed_assets","type":"ASSET"},
    {"id":"special_inv_funds","name":"Special Inv. Funds","parent":"investments","type":"ASSET"},
    {"id":"stock_in_trade","name":"Stock-in-Trade","parent":"investments","type":"ASSET"},
    {"id":"stocks","name":"Stocks","parent":"investments","type":"ASSET"},
    {"id":"stt","name":"STT","parent":"expenses","type":"EXPENSE"},
    {"id":"sundry_creditors","name":"Sundry Creditors","type":"LIABILITY"},
    {"id":"tax_charges_stocks","name":"Tax & Charges - Stocks","parent":"expenses","type":"EXPENSE"},
    {"id":"traded_bonds","name":"Traded Bonds","parent":"investments","type":"ASSET"}
  ],
  "ledgers": [
    {"id":"l1","name":"Krisha Shah","groupId":"capital_account","openingBalance":0,"openingType":"CR"},
    {"id":"l2","name":"Pramesh Shah","groupId":"capital_account","openingBalance":0,"openingType":"CR"},
    {"id":"l3","name":"Sauhil Shah","groupId":"capital_account","openingBalance":0,"openingType":"CR"},
    {"id":"l4","name":"Unnati Shah","groupId":"capital_account","openingBalance":0,"openingType":"CR"},
    {"id":"l5","name":"Capital Account","groupId":"capital_account","openingBalance":483277,"openingType":"CR"},
    {"id":"l6","name":"Interest On Saving Account","groupId":"interest_saving","openingBalance":911,"openingType":"CR"},
    {"id":"l7","name":"Long Term Gain (Equity)","groupId":"capital_gains","openingBalance":4971.73,"openingType":"DR"},
    {"id":"l8","name":"STT - MPr","groupId":"stt","openingBalance":0.55,"openingType":"DR"},
    {"id":"l9","name":"Jewellery","groupId":"jewellery","openingBalance":307500,"openingType":"DR"},
    {"id":"l10","name":"BANDHAN Arbitrage Fund-Direct Plan- Growth (6341159/66)","groupId":"mf_equity","openingBalance":35000,"openingType":"DR"},
    {"id":"l11","name":"Edelweiss Nifty Midcap150 Momentum 50 Index Fund - Direct Plan - Growth (91044592493 / 0)","groupId":"mf_equity","openingBalance":10000,"openingType":"DR"},
    {"id":"l12","name":"Edelweiss Nifty500 Multicap Momentum Quality 50 Index Fund - Direct - Gr...","groupId":"mf_equity","openingBalance":10000,"openingType":"DR"},
    {"id":"l13","name":"ICICI Prudential Dividend Yield Equity Fund Direct Plan Growth Option (34030122/30)","groupId":"mf_equity","openingBalance":20000,"openingType":"DR"},
    {"id":"l14","name":"JM Flexicap Fund (Direct) - Growth Option (79915382765 / 0)","groupId":"mf_equity","openingBalance":0,"openingType":"DR"},
    {"id":"l15","name":"Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF Fund of Fund -...","groupId":"mf_equity","openingBalance":25000,"openingType":"DR"},
    {"id":"l16","name":"Quant Mid Cap Fund Growth Option Direct Plan (51074476855 / 0)","groupId":"mf_equity","openingBalance":0,"openingType":"DR"},
    {"id":"l17","name":"Quant Small Cap Fund-Growth Option-Direct Plan (51074476845 / 0)","groupId":"mf_equity","openingBalance":0,"openingType":"DR"},
    {"id":"l18","name":"SBI Contra Fund - Direct Plan - Growth (38067944)","groupId":"mf_equity","openingBalance":20000,"openingType":"DR"},
    {"id":"l19","name":"Cash on Hand","groupId":"cash","openingBalance":504,"openingType":"DR"},
    {"id":"l20","name":"Kotak Bank (A/c. No. - 5348805437)","groupId":"bank","openingBalance":51211.72,"openingType":"DR"}
  ],
  "vouchers": [],
  "entries": []
}

print(json.dumps(data, indent=2))
